# Generated by Django 2.2 on 2020-11-06 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('class_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=10)),
                ('section', models.CharField(choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('roll_number', models.CharField(max_length=5)),
                ('maths', models.FloatField(max_length=3)),
                ('english', models.FloatField(max_length=3)),
                ('social', models.FloatField(max_length=3)),
                ('evs', models.FloatField(max_length=3)),
                ('hindi', models.FloatField(max_length=3)),
                ('total', models.FloatField(max_length=3)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
