# Generated by Django 2.2 on 2020-11-06 10:44

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='student_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='english',
            field=models.FloatField(max_length=5, validators=[student.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='students',
            name='evs',
            field=models.FloatField(max_length=5, validators=[student.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='students',
            name='hindi',
            field=models.FloatField(max_length=5, validators=[student.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='students',
            name='maths',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='students',
            name='social',
            field=models.FloatField(max_length=5, validators=[student.models.validate_decimals]),
        ),
        migrations.AlterField(
            model_name='students',
            name='total',
            field=models.FloatField(max_length=5, validators=[student.models.validate_decimals]),
        ),
    ]
